DEBUG = True

ORGANISATION_NAME = 'Squad'
ORGANISATION_DOMAIN = 'squad.nl'
APPLICATION_NAME = 'StickMaps'
APPLICATION_ICON = 'Assets/windowIcon.png'
APPLICATION_VERSION = 0.1
APPLICATION_FILE_EXTENSION = 'stk'

MAIN_WINDOW_TITLE = APPLICATION_NAME
MAIN_WINDOW_ICON = APPLICATION_ICON
MAIN_WINDOW_STATUSBAR_TIMEOUT = 3000

TREE_START_WIDTH = 300
TREE_MIN_WIDTH = 100

TREE_LIGHT_ICON_SURVEY = 'Assets/surveyIcon.png'
TREE_LIGHT_ICON_SECTION = 'Assets/sectionIcon.png'
TREE_LIGHT_ICON_STATION = 'Assets/pointIcon.png'

TREE_DARK_ICON_SURVEY = 'Assets/surveyIcon.png'
TREE_DARK_ICON_SECTION = 'Assets/sectionIcon.png'
TREE_DARK_ICON_STATION = 'Assets/pointIcon.png'

DEVICE_NAME_MNEMO = "Mnemo"

#SQL_DB_LOCATION = ":memory:"
SQL_DB_LOCATION = "/tmp/stickmaps.sql"
SQL_CONNECTION_NAME = "qt_sql_default_connection"
SQL_TABLE_SURVEYS = "surveys"
SQL_TABLE_SECTIONS = "sections"
SQL_TABLE_STATIONS = "stations"
SQL_TABLE_CONTACTS = "contacts"
SQL_TABLE_EXPLORERS = "explorers"
SQL_TABLE_SURVEYORS = "surveyors"