APPLICATION_VERSION = 0.1
APPLICATION_NAME = 'StickMaps'
APPLICATION_FILE_EXTENSION = 'stk'
MAIN_WINDOW_TITLE = APPLICATION_NAME
MAIN_WINDOW_ICON = 'Assets/windowIcon.png'
MAIN_WINDOW_STATUSBAR_TIMEOUT = 3000

TREE_START_WIDTH = 300
TREE_MIN_WIDTH = 100



TREE_ICON_SURVEY = 'Assets/surveyIcon.png'
TREE_ICON_SECTION = 'Assets/sectionIcon.png'
TREE_ICON_POINT = 'Assets/pointIcon.png'

DEVICE_NAME_MNEMO = "Mnemo"

#SQL_DB_LOCATION = ":memory:"
SQL_DB_LOCATION = "/tmp/stickmaps.sql"
SQL_TABLE_SURVEYS = "surveys"
SQL_TABLE_SECTIONS = "sections"
SQL_TABLE_POINTS = "points"
SQL_TABLE_CONTACTS = "contacts"
SQL_TABLE_EXPLORERS = "explorers"
SQL_TABLE_SURVEYORS = "surveyors"