DEBUG = True

ORGANISATION_NAME = 'Squad'
ORGANISATION_DOMAIN = 'squad.nl'
APPLICATION_NAME = 'StickMaps'
APPLICATION_ICON = 'Assets/windowIcon.png'
APPLICATION_VERSION = 0.1
APPLICATION_FILE_EXTENSION = 'stk'

MAIN_WINDOW_TITLE = APPLICATION_NAME
MAIN_WINDOW_ICON = APPLICATION_ICON
MAIN_WINDOW_STATUSBAR_TIMEOUT = 3000

TREE_START_WIDTH = 300
TREE_MIN_WIDTH = 100

TREE_LIGHT_ICON_SURVEY = 'Assets/surveyIcon.png'
TREE_LIGHT_ICON_LINE = 'Assets/sectionIcon.png'
TREE_LIGHT_ICON_STATION = 'Assets/pointIcon.png'

TREE_DARK_ICON_SURVEY = 'Assets/surveyIcon.png'
TREE_DARK_ICON_LINE = 'Assets/sectionIcon.png'
TREE_DARK_ICON_STATION = 'Assets/pointIcon.png'

MNEMO_DEVICE_NAME = "Mnemo"
MNEMO_DEVICE_DESCRIPTION = "MCP2221 USB-I2C/UART Combo"
MNEMO_BAUDRATE = 9600
MNEMO_TIMEOUT = 1
MNEMO_CYCLE_COUNT = 50

SURVEY_DIRECTION_IN = "In"
SURVEY_DIRECTION_OUT = "Out"

#SQL_DB_LOCATION = ":memory:"
SQL_DB_LOCATION = "/tmp/stickmaps.sqlite"
SQL_CONNECTION_NAME = "qt_sql_default_connection"
SQL_TABLE_IMPORT_SURVEYS = "import_surveys"
SQL_TABLE_IMPORT_LINES = "import_lines"
SQL_TABLE_IMPORT_STATIONS = "import_stations"
SQL_TABLE_MAP_LINES = "map_lines"
SQL_TABLE_MAP_STATIONS = "map_stations"
SQL_TABLE_CONTACTS = "contacts"
SQL_TABLE_EXPLORERS = "explorers"
SQL_TABLE_SURVEYORS = "surveyors"

# preference defaults
